In [1]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [8]:
df = pd.read_excel(r"C:\Users\HP\Downloads\Sample - Superstore.xls")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [9]:
la = df[df["City"] == "Los Angeles"]
la

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,9977,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.584,2,0.2,31.1980
9977,9978,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.860,7,0.0,0.0000
9978,9979,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,13.376,4,0.2,4.6816
9979,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152
9986,9987,CA-2016-125794,2016-09-29,2016-10-03,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208

In [12]:
highest = la.groupby("Customer Name")["Sales"].count()
highest.sort_values(ascending = False)[:5]

Customer Name
Arthur Prichep    10
Clay Ludtke       10
Greg Guthrie       9
William Brown      9
Arianne Irving     8
Name: Sales, dtype: int64

In [13]:
segment = df.groupby("Segment")["Sales"].sum()
print(segment)

Segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: Sales, dtype: float64

In [14]:
state = df.groupby("State")["Sales"].sum()
print(state)

State
Alabama                  19510.6400
Arizona                  35282.0010
Arkansas                 11678.1300
California              457687.6315
Colorado                 32108.1180
Connecticut              13384.3570
Delaware                 27451.0690
District of Columbia      2865.0200
Florida                  89473.7080
Georgia                  49095.8400
Idaho                     4382.4860
Illinois                 80166.1010
Indiana                  53555.3600
Iowa                      4579.7600
Kansas                    2914.3100
Kentucky                 36591.7500
Louisiana                 9217.0300
Maine                     1270.5300
Maryland                 23705.5230
Massachusetts            28634.4340
Michigan                 76269.6140
Minnesota                29863.1500
Mississippi              10771.3400
Missouri                 22205.1500
Montana                   5589.3520
Nebraska                  7464.9300
Nevada                   16729.1020
New Hampshire             7292.5240
New Jersey               35764.3120
New Mexico                4783.5220
New York                310876.2710
North Carolina           55603.1640
North Dakota               919.9100
Ohio                     78258.1360
Oklahoma                 19683.3900
Oregon                   17431.1500
Pennsylvania            116511.9140
Rhode Island             22627.9560
South Carolina            8481.7100
South Dakota              1315.5600
Tennessee                30661.8730
Texas                   170188.0458
Utah                     11220.0560
Vermont                   8929.3700
Virginia                 70636.7200
Washington              138641.2700
West Virginia             1209.8240
Wisconsin                32114.6100
Wyoming                   1603.1360
Name: Sales, dtype: float64

In [19]:
Customer_Name = df.groupby("Customer_Name")["Sales"].sum()
print(Customer_Name)

KeyError: 'Customer_Name'

In [20]:
region_total = df.groupby("Region")["Sales"].sum()
print(region_total)

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [21]:
biggest_region = region_total.idxmax()
print(biggest_region)

West

In [23]:
henderson = df[df["City"] == "Henderson"]
henderson

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
538,539,CA-2015-134894,2015-12-07,2015-12-11,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,...,42420,South,OFF-AP-10001271,Office Supplies,Appliances,Eureka The Boss Cordless Rechargeable Stick Vac,152.940,3,0.0,41.2938
539,540,CA-2015-134894,2015-12-07,2015-12-11,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,...,42420,South,FUR-CH-10002647,Furniture,Chairs,"Situations Contoured Folding Chairs, 4/Set",283.920,4,0.0,70.9800
996,997,CA-2015-162537,2015-10-28,2015-11-03,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,OFF-EN-10003862,Office Supplies,Envelopes,Laser & Ink Jet Business Envelopes,10.670,1,0.0,4.9082
997,998,CA-2015-162537,2015-10-28,2015-11-03,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,OFF-ST-10004258,Office Supplies,Storage,Portable Personal File Box,36.630,3,0.0,9.8901
998,999,CA-2015-162537,2015-10-28,2015-11-03,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,FUR-FU-10002885,Furniture,Furnishings,Magna Visual Magnetic Picture Hangers,24.100,5,0.0,9.1580
999,1000,CA-2015-162537,2015-10-28,2015-11-03,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,FUR-FU-10001918,Furniture,Furnishings,C-Line Cubicle Keepers Polyproplyene Holder Wi...,33.110,7,0.0,12.9129
1866,1867,CA-2017-118857,2017-04-15,2017-04-18,First Class,AH-10075,Adam Hart,Corporate,United States,Henderson,...,89015,West,FUR-FU-10004460,Furniture,Furnishings,"Howard Miller 12"" Round Wall Clock",196.450,5,0.0,70.7220
2321,2322,CA-2015-109470,2015-12-31,2016-01-03,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10004492,Office Supplies,Binders,Tuf-Vin Binders,94.740,3,0.0,44.5278
2322,2323,CA-2015-109470,2015-12-31,2016-01-03,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10001072,Office Supplies,Binders,"GBC Clear Cover, 8-1/2 x 11, unpunched, 25 cov...",60.640,4,0.0,27.8944
2323,2324,CA-2015-109470,2015-12-31,2016-01-03,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10003707,Office Supplies,Binders,Aluminum Screw Posts,76.300,5,0.0,38.1500
2324,2325,CA-2015-109470,2015-12-31,2016-01-03,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10000977,Office Supplies,Binders,Ibico Plastic Spiral Binding Combs,364.800,12,0.0,167.8080
2551,2552,CA-2017-101042,2017-11-19,2017-11-23,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Henderson,...,42420,South,FUR-FU-10004665,Furniture,Furnishings,"3M Polarizing Task Lamp with Clamp Arm, Light ...",821.880,6,0.0,213.6888
2552,2553,CA-2017-101042,2017-11-19,2017-11-23,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Henderson,...,42420,South,OFF-BI-10000088,Office Supplies,Binders,GBC Imprintable Covers,21.960,2,0.0,10.7604
3088,3089,US-2017-159205,2017-03-31,2017-04-02,Second Class,DB-12910,Daniel Byrd,Home Office,United States,Henderson,...,42420,South,FUR-FU-10001591,Furniture,Furnishings,Advantus Panel Wall Certificate Holder - 8.5x11,61.000,5,0.0,25.6200
3089,3090,US-2017-159205,2017-03-31,2017-04-02,Second Class,DB-12910,Daniel Byrd,Home Office,United States,Henderson,...,42420,South,TEC-PH-10000526,Technology,Phones,Vtech CS6719,671.930,7,0.0,188.1404
3537,3538,CA-2014-158771,2014-05-09,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250,3,0.0,14.9850
3538,3539,CA-2014-158771,2014-05-09,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-LA-10001641,Office Supplies,Labels,Avery 518,9.450,3,0.0,4.5360
3539,3540,CA-2014-158771,2014-05-09,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-LA-10003121,Office Supplies,Labels,Avery 506,20.650,5,0.0,9.4990
3540,3541,CA-2014-158771,2014-05-09,2014-05-09,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.360,7,0.0,21.7728
4378,4379,CA-2015-140830,2015-11-30,2015-12-02,Second Class,PS-18970,Paul Stevenson,Home Office,United States,Henderson,...,42420,South,OFF-EN-10000461,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Recycled Envelopes",17.480,2,0.0,8.2156
4379,4380,CA-2015-140830,2015-11-30,2015-12-02,Second Class,PS-18970,Paul Stevenson,Home Office,United States,Henderson,...,42420,South,OFF-EN-10002831,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Gray",71.880,2,0.0,32.3460
4430,4431,CA-2016-168893,2016-11-03,2016-11-08,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,OFF-FA-10002280,Office Supplies,Fasteners,Advantus Plastic Paper Clips,20.000,4,0.0,9.6000
4431,4432,CA-2016-168893,2016-11-03,2016-11-08,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,OFF-AR-10001770,Office Supplies,Art,Economy #2 Pencils,7.980,3,0.0,2.0748
4432,4433,CA-2016-168893,2016-11-03,2016-11-08,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,FUR-FU-10002885,Furniture,Furnishings,Magna Visual Magnetic Picture Hangers,24.100,5,0.0,9.1580
4433,4434,CA-2016-168893,2016-11-03,2016-11-08,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,OFF-AR-10003772,Office Supplies,Art,Boston 16750 Black Compact Battery Pencil Shar...,8.750,1,0.0,2.6250
4434,4435,CA-2016-168893,2016-11-03,2016-11-08,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,FUR-TA-10003392,Furniture,Tables,Global Adaptabilities Conference Tables,842.940,3,0.0,160.1586
4840,4841,CA-2017-154123,2017-11-20,2017-11-25,Standard Class,SC-20050,Sample Company A,Home Office,United States,Henderson,...,42420,South,FUR-FU-10000629,Furniture,Furnishings,9-3/4 Diameter Round Wall Clock,27.580,2,0.0,11.5836
4879,4880,CA-2017-143567,2017-11-02,2017-11-05,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,OFF-EN-10004846,Office Supplies,Envelopes,Letter or Legal Size Expandable Poly String Ti...,5.320,2,0.0,2.6068
4880,4881,CA-2017-143567,2017-11-02,2017-11-05,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",975.920,4,0.0,292.7760
4881,4882,CA-2017-143567,2017-11-02,2017-11-05,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,2249.910,9,0.0,517.4793
4882,4883,CA-2017-143567,2017-11-02,2017-11-05,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,OFF-ST-10001580,Office Supplies,Storage,Super Decoflex Portable Personal File,59.920,4,0.0,16.7776
7090,7091,CA-2015-119480,2015-01-09,2015-01-13,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,106.320,3,0.0,49.9704
7091,7092,CA-2015-119480,2015-01-09,2015-01-13,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-AP-10001205,Office Supplies,Appliances,Belkin 5 Outlet SurgeMaster Power Centers,163.440,3,0.0,45.7632
7092,7093,CA-2015-119480,2015-01-09,2015-01-13,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-AR-10004691,Office Supplies,Art,Boston 1730 StandUp Electric Pencil Sharpener,42.760,2,0.0,11.1176
7093,7094,CA-2015-119480,2015-01-09,2015-01-13,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-PA-10004996,Office Supplies,Paper,"Speediset Carbonless Redi-Letter 7"" x 8 1/2""",51.550,5,0.0,24.2285
7114,7115,US-2016-102239,2016-05-05,2016-05-06,First Class,LW-16990,Lindsay Williams,Corporate,United States,Henderson,...,89015,West,FUR-TA-10003392,Furniture,Tables,Global Adaptabilities Conference Tables,1685.880,6,0.0,320.3172
7115,7116,US-2016-102239,2016-05-05,2016-05-06,First Class,LW-16990,Lindsay Williams,Corporate,United States,Henderson,...,89015,West,OFF-BI-10001890,Office Supplies,Binders,Avery Poly Binder Pockets,5.728,2,0.2,2.0048
7474,7475,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
7475,7476,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2,0.0,274.4910
7476,7477,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796
7477,7478,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004977,Technology,Phones,GE 30524EE4,391.980,2,0.0,113.6742
7478,7479,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.960,4,0.0,204.1092
7479,7480,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-FA-10001883,Office Supplies,Fasteners,"Alliance Super-Size Bands, Assorted Sizes",31.120,4,0.0,0.3112
7480,7481,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-PA-10000955,Office Supplies,Paper,Southworth 25% Cotton Granite Paper & Envelopes,6.540,1,0.0,3.0084
8639,8640,CA-2014-129819,2014-12-13,2014-12-15,Second Class,KC-16675,Kimberly Carter,Corporate,United States,Henderson,...,42420,South,OFF-BI-10004970,Office Supplies,Binders,"ACCOHIDE 3-Ring Binder, Blue, 1""",12.390,3,0.0,5.8233
9074,9075,CA-2014-136336,2014-04-21,2014-04-26,Standard Class,DB-13555,Dorothy Badders,Corporate,United States,Henderson,...,42420,South,OFF-ST-10002574,Office Supplies,Storage,"SAFCO Commercial Wire Shelving, Black",828.840,6,0.0,0.0000
9078,9079,CA-2016-108105,2016-02-16,2016-02-23,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Henderson,...,42420,South,FUR-FU-10003773,Furniture,Furnishings,Eldon Cleatmat Plus Chair Mats for High Pile C...,318.080,4,0.0,34.9888
9079,9080,CA-2016-108105,2016-02-16,2016-02-23,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Henderson,...,42420,South,OFF-BI-10002412,Office Supplies,Binders,Wilson Jones “Snap” Scratch Pad Binder Tool fo...,5.800,1,0.0,2.6100
9273,9274,CA-2017-146983,2017-09-02,2017-09-06,Standard Class,AH-10210,Alan Hwang,Consumer,United States,Henderson,...,42420,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,1577.940,3,0.0,757.4112

In [24]:
highest = henderson.groupby("Product Name")["Sales"].count()
highest.sort_values(ascending = False)[:5]

Product Name
Global Adaptabilities Conference Tables                        2
Magna Visual Magnetic Picture Hangers                          2
Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back    2
#10- 4 1/8" x 9 1/2" Recycled Envelopes                        1
Advantus Panel Wall Certificate Holder - 8.5x11                1
Name: Sales, dtype: int64

In [34]:
df.groupby("sub-category"),["Profit"].sum().sort_values(ascending=False).head(3).index

KeyError: 'sub-category'

In [25]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\HP\Downloads\final_dataset.csv")
df

,Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0,1,1,2021,0,5,408.80,442.42,160.61,12.95,2.77,43.19,462
1,2,1,2021,0,6,404.04,561.95,52.85,5.18,2.60,16.43,482
2,3,1,2021,1,7,225.07,239.04,170.95,10.93,1.40,44.29,263
3,4,1,2021,0,1,89.55,132.08,153.98,10.42,1.01,49.19,207
4,5,1,2021,0,2,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,27,12,2024,0,5,58.43,249.17,41.69,65.89,0.99,36.25,263
1457,28,12,2024,0,6,33.83,150.77,33.31,66.14,0.79,35.19,113
1458,29,12,2024,1,7,31.21,139.75,27.01,65.94,0.57,35.88,142
1459,30,12,2024,0,1,38.01,152.83,29.12,65.16,0.55,38.38,116
1460,31,12,2024,0,2,80.42,318.96,40.37,64.98,0.84,39.93,209

In [5]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\HP\Desktop\shubham\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\HP\Desktop\shubham\Lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [83]:
import pandas as pd 
df = pd.read_excel(r"C:\Users\HP\Downloads\Forbes_2000_Companies_2025.xlsx")
df.head()

,Rank,Company,Headquarters,Industry,Sales ($B),Profit ($B),Assets ($B),Market Value ($B)
0,1,JPMorganChase,United States,Banking,285.11,59.36,4357.86,677.80
1,2,Berkshire Hathaway,United States,Insurance,371.43,89.00,1153.88,1145.46
2,3,ICBC,China,Banking,221.96,50.84,6688.60,251.33
3,4,Saudi Arabian Oil Company (Saudi Aramco),Saudi Arabia,Oil & Gas Operations,480.15,104.97,645.03,1663.38
4,5,Amazon,United States,Retail and Wholesale,637.96,59.25,624.89,2005.64

In [84]:
col = []
for i in df.columns:
    if" ($B)" in i:
        col.append(i.replace(" ($B)",""))
    else:
        col.append(i)
df.columns = col

In [85]:
print(col)

['Rank', 'Company', 'Headquarters', 'Industry', 'Sales', 'Profit', 'Assets', 'Market Value']

In [86]:
df["profit Margin"] = df["Profit"] / df["Sales"]

In [87]:
print(df.head())

   Rank                                   Company   Headquarters  \
0     1                             JPMorganChase  United States
1     2                        Berkshire Hathaway  United States
2     3                                      ICBC          China
3     4  Saudi Arabian Oil Company (Saudi Aramco)   Saudi Arabia
4     5                                    Amazon  United States

               Industry   Sales  Profit   Assets  Market Value  profit Margin
0               Banking  285.11   59.36  4357.86        677.80       0.208200
1             Insurance  371.43   89.00  1153.88       1145.46       0.239614
2               Banking  221.96   50.84  6688.60        251.33       0.229050
3  Oil & Gas Operations  480.15  104.97   645.03       1663.38       0.218619
4  Retail and Wholesale  637.96   59.25   624.89       2005.64       0.092874

In [88]:
df["Sales"]

0       285.110
1       371.430
2       221.960
3       480.150
4       637.960
         ...
1995      7.360
1996     15.520
1997      8.790
1998      0.474
1999      0.716
Name: Sales, Length: 2000, dtype: float64

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           2000 non-null   int64
 1   Company        2000 non-null   str
 2   Headquarters   2000 non-null   str
 3   Industry       2000 non-null   str
 4   Sales          2000 non-null   float64
 5   Profit         1998 non-null   float64
 6   Assets         2000 non-null   float64
 7   Market Value   2000 non-null   float64
 8   profit Margin  1998 non-null   float64
dtypes: float64(5), int64(1), str(3)
memory usage: 217.7 KB

In [90]:
df.isnull().sum()

Rank             0
Company          0
Headquarters     0
Industry         0
Sales            0
Profit           2
Assets           0
Market Value     0
profit Margin    2
dtype: int64

In [91]:
df["Profit"].fillna(df["Profit"].mean() , inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_12896\3510829014.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Profit"].fillna(df["Profit"].mean() , inplace = True)

0        59.3600
1        89.0000
2        50.8400
3       104.9700
4        59.2500
          ...
1995      0.3781
1996      0.0784
1997      0.6288
1998      0.0927
1999      1.1800
Name: Profit, Length: 2000, dtype: float64

In [92]:
df

,Rank,Company,Headquarters,Industry,Sales,Profit,Assets,Market Value,profit Margin
0,1,JPMorganChase,United States,Banking,285.110,59.3600,4357.86,677.800,0.208200
1,2,Berkshire Hathaway,United States,Insurance,371.430,89.0000,1153.88,1145.460,0.239614
2,3,ICBC,China,Banking,221.960,50.8400,6688.60,251.330,0.229050
3,4,Saudi Arabian Oil Company (Saudi Aramco),Saudi Arabia,Oil & Gas Operations,480.150,104.9700,645.03,1663.380,0.218619
4,5,Amazon,United States,Retail and Wholesale,637.960,59.2500,624.89,2005.640,0.092874
...,...,...,...,...,...,...,...,...,...
1995,1996,Dino Polska,Poland,Food Markets,7.360,0.3781,3.16,13.840,0.051372
1996,1997,China Aviation Oil,Singapore,Trading Companies,15.520,0.0784,1.99,0.559,0.005052
1997,1998,Jet2,United Kingdom,Business Services & Supplies,8.790,0.6288,7.95,3.930,0.071536
1998,1998,Keiyo Bank,Japan,Banking,0.474,0.0927,42.56,0.679,0.195570
1999,1998,PT Lippo Karawaci,Indonesia,Construction,0.716,1.1800,3.34,0.366,1.648045

In [94]:
print(df.columns)

Index(['Rank', 'Company', 'Headquarters', 'Industry', 'Sales', 'Profit',
       'Assets', 'Market Value', 'profit Margin'],
      dtype='str')

In [97]:

l = []
for i in df["profit Margin"]:
    l.append(f"{(i*100)//1}%")
print(l)

['20.0%', '23.0%', '22.0%', '21.0%', '9.0%', '14.0%', '23.0%', '19.0%', '30.0%', '35.0%', '24.0%', '18.0%', '9.0%', '10.0%', '15.0%', '16.0%', '5.0%', '2.0%', '11.0%', '12.0%', '37.0%', '7.0%', '5.0%', '14.0%', '6.0%', '13.0%', '11.0%', '5.0%', '9.0%', '9.0%', '13.0%', '13.0%', '12.0%', '15.0%', '9.0%', '7.0%', '29.0%', '41.0%', '29.0%', '9.0%', '8.0%', '24.0%', '12.0%', '7.0%', '7.0%', '7.0%', '55.0%', '11.0%', '14.0%', '13.0%', '1.0%', '11.0%', '15.0%', '3.0%', '12.0%', '13.0%', '16.0%', '8.0%', '14.0%', '18.0%', '16.0%', '12.0%', '14.0%', '5.0%', '6.0%', '21.0%', '9.0%', '18.0%', '6.0%', '6.0%', '6.0%', '7.0%', '12.0%', '1.0%', '18.0%', '27.0%', '15.0%', '8.0%', '8.0%', '13.0%', '5.0%', '12.0%', '4.0%', '10.0%', '33.0%', '10.0%', '5.0%', '9.0%', '26.0%', '9.0%', '5.0%', '9.0%', '2.0%', '16.0%', '8.0%', '11.0%', '5.0%', '3.0%', '7.0%', '23.0%', '7.0%', '8.0%', '3.0%', '22.0%', '16.0%', '8.0%', '8.0%', '7.0%', '13.0%', '15.0%', '17.0%', '12.0%', '28.0%', '4.0%', '17.0%', '38.0%', '4.0%', '16.0%', '6.0%', '1.0%', '14.0%', '13.0%', '17.0%', '24.0%', '21.0%', '53.0%', '3.0%', '6.0%', '11.0%', '12.0%', '13.0%', '11.0%', '5.0%', '19.0%', '21.0%', '2.0%', '2.0%', '23.0%', '6.0%', '12.0%', '12.0%', '7.0%', '12.0%', '31.0%', '9.0%', '17.0%', '16.0%', '15.0%', '12.0%', '9.0%', '6.0%', '5.0%', '28.0%', '23.0%', '36.0%', '15.0%', '11.0%', '34.0%', '5.0%', '11.0%', '4.0%', '22.0%', '6.0%', '16.0%', '28.0%', '10.0%', '9.0%', '9.0%', '18.0%', '22.0%', '3.0%', '6.0%', '11.0%', '14.0%', '6.0%', '5.0%', '19.0%', '16.0%', '19.0%', '3.0%', '17.0%', '14.0%', '4.0%', '11.0%', '9.0%', '3.0%', '7.0%', '8.0%', '23.0%', '9.0%', '29.0%', '14.0%', '7.0%', '25.0%', '0.0%', '11.0%', '16.0%', '17.0%', '22.0%', '11.0%', '8.0%', '12.0%', '7.0%', '8.0%', '2.0%', '8.0%', '13.0%', '20.0%', '11.0%', '12.0%', '10.0%', '4.0%', '27.0%', '28.0%', '6.0%', '10.0%', '45.0%', '15.0%', '3.0%', '5.0%', '2.0%', '22.0%', '34.0%', '31.0%', '12.0%', '12.0%', '21.0%', '14.0%', '27.0%', '6.0%', '2.0%', '18.0%', '20.0%', '4.0%', '8.0%', '8.0%', '5.0%', '10.0%', '13.0%', '21.0%', '15.0%', '8.0%', '3.0%', '20.0%', '36.0%', '2.0%', '10.0%', '9.0%', '14.0%', '9.0%', '11.0%', '9.0%', '10.0%', '10.0%', '15.0%', '20.0%', '28.0%', '3.0%', '9.0%', '6.0%', '1.0%', '12.0%', '5.0%', '5.0%', '8.0%', '8.0%', '16.0%', '14.0%', '8.0%', '15.0%', '12.0%', '7.0%', '9.0%', '58.0%', '11.0%', '1.0%', '17.0%', '8.0%', '9.0%', '21.0%', '5.0%', '5.0%', '20.0%', '2.0%', '11.0%', '19.0%', '0.0%', '12.0%', '11.0%', '9.0%', '13.0%', '18.0%', '14.0%', '16.0%', '18.0%', '11.0%', '15.0%', '27.0%', '3.0%', '22.0%', '9.0%', '11.0%', '5.0%', '9.0%', '1.0%', '7.0%', '10.0%', '9.0%', '5.0%', '6.0%', '15.0%', '0.0%', '5.0%', '6.0%', '6.0%', '13.0%', '15.0%', '25.0%', '12.0%', '7.0%', '15.0%', '10.0%', '5.0%', '21.0%', '54.0%', '1.0%', '18.0%', '15.0%', '14.0%', '13.0%', '13.0%', '9.0%', '11.0%', '17.0%', '1.0%', '7.0%', '5.0%', '11.0%', '13.0%', '30.0%', '9.0%', '3.0%', '27.0%', '22.0%', '2.0%', '17.0%', '6.0%', '2.0%', '23.0%', '4.0%', '12.0%', '14.0%', '24.0%', '18.0%', '17.0%', '38.0%', '3.0%', '1.0%', '7.0%', '24.0%', '7.0%', '14.0%', '11.0%', '21.0%', '12.0%', '9.0%', '15.0%', '11.0%', '16.0%', '16.0%', '2.0%', '5.0%', '0.0%', '30.0%', '13.0%', '7.0%', '11.0%', '21.0%', '9.0%', '2.0%', '25.0%', '2.0%', '22.0%', '2.0%', '16.0%', '13.0%', '20.0%', '15.0%', '6.0%', '6.0%', '11.0%', '8.0%', '15.0%', '17.0%', '19.0%', '5.0%', '0.0%', '12.0%', '1.0%', '10.0%', '29.0%', '3.0%', '17.0%', '10.0%', '13.0%', '17.0%', '11.0%', '28.0%', '19.0%', '2.0%', '9.0%', '8.0%', '6.0%', '5.0%', '20.0%', '6.0%', '44.0%', '19.0%', '30.0%', '1.0%', '0.0%', '13.0%', '3.0%', '2.0%', '11.0%', '6.0%', '20.0%', '3.0%', '1.0%', '18.0%', '16.0%', '14.0%', '31.0%', '12.0%', '2.0%', '15.0%', '13.0%', '18.0%', '12.0%', '14.0%', '18.0%', '22.0%', '22.0%', '17.0%', '11.0%', '20.0%', '3.0%', '2.0%', '-17.0%', '9.0%', '7.0%', '6.0%', '5.0%', '11.0%', '13.0%', '10.0%', '5.0%', '5.0%', '25.0%', '5.0%', '14.0%', '7.0%', '5.0%', '20.0%', '10.0%', '16.0%', '3.0%', '57.0%', '8.0%', '8.0%', '29.0%', '9.0%', '16.0%', '2.0%', '31.0%', '8.0%', '14.0%', '57.0%', '8.0%', '27.0%', '26.0%', '45.0%', '23.0%', '9.0%', '9.0%', '27.0%', '7.0%', '8.0%', '-37.0%', '12.0%', '12.0%', '1.0%', '20.0%', '25.0%', '6.0%', '6.0%', '5.0%', '9.0%', '9.0%', '6.0%', '28.0%', '3.0%', '21.0%', '12.0%', '17.0%', '27.0%', '4.0%', '10.0%', '6.0%', '20.0%', '5.0%', '19.0%', '2.0%', '1.0%', '-1.0%', '24.0%', '13.0%', '7.0%', '6.0%', '15.0%', '7.0%', '1.0%', '15.0%', '12.0%', '22.0%', '4.0%', '16.0%', '6.0%', '24.0%', '12.0%', '6.0%', '3.0%', '1.0%', '10.0%', '23.0%', '2.0%', '12.0%', '20.0%', '10.0%', '7.0%', '19.0%', '16.0%', '2.0%', '21.0%', '6.0%', '19.0%', '10.0%', '14.0%', '3.0%', '9.0%', '5.0%', '3.0%', '42.0%', '8.0%', '16.0%', '16.0%', '10.0%', '18.0%', '16.0%', '8.0%', '24.0%', '16.0%', '9.0%', '8.0%', '1.0%', '36.0%', '11.0%', '12.0%', '13.0%', '14.0%', '33.0%', '2.0%', '9.0%', '17.0%', '48.0%', '8.0%', '15.0%', '22.0%', '10.0%', '14.0%', '13.0%', '2.0%', '21.0%', '13.0%', '7.0%', '2.0%', '6.0%', '263.0%', '21.0%', '5.0%', '12.0%', '6.0%', '8.0%', '8.0%', '12.0%', '13.0%', '8.0%', '2.0%', '19.0%', '22.0%', '5.0%', '8.0%', '6.0%', '2.0%', '11.0%', '19.0%', '18.0%', '18.0%', '-3.0%', '7.0%', '11.0%', '5.0%', '9.0%', '9.0%', '7.0%', '15.0%', '5.0%', '-6.0%', '0.0%', '2.0%', '2.0%', '22.0%', '26.0%', '35.0%', '-1.0%', '-1.0%', '21.0%', '1.0%', '6.0%', '3.0%', '7.0%', '20.0%', '23.0%', '5.0%', '6.0%', '0.0%', '14.0%', '5.0%', '12.0%', '7.0%', '9.0%', '8.0%', '10.0%', '9.0%', '13.0%', '9.0%', '1.0%', '3.0%', '6.0%', '20.0%', '5.0%', '7.0%', '15.0%', '14.0%', '2.0%', '17.0%', '1.0%', '3.0%', '11.0%', '6.0%', '5.0%', '18.0%', '20.0%', '12.0%', '2.0%', '9.0%', '4.0%', '3.0%', '29.0%', '17.0%', '3.0%', '-29.0%', '1.0%', '6.0%', '28.0%', '3.0%', '13.0%', '14.0%', '0.0%', '3.0%', '8.0%', '1.0%', '7.0%', '3.0%', '6.0%', '27.0%', '14.0%', '7.0%', '11.0%', '7.0%', '15.0%', '-12.0%', '20.0%', '8.0%', '5.0%', '16.0%', '30.0%', '12.0%', '384.0%', '5.0%', '9.0%', '11.0%', '36.0%', '1.0%', '5.0%', '31.0%', '4.0%', '0.0%', '29.0%', '10.0%', '2.0%', '12.0%', '8.0%', '5.0%', '25.0%', '7.0%', '9.0%', '13.0%', '8.0%', '11.0%', '16.0%', '3.0%', '11.0%', '37.0%', '7.0%', '12.0%', '58.0%', '14.0%', '8.0%', '15.0%', '5.0%', '69.0%', '10.0%', '26.0%', '8.0%', '2.0%', '4.0%', '1529.0%', '22.0%', '7.0%', '14.0%', '6.0%', '0.0%', '12.0%', '10.0%', '35.0%', '9.0%', '4.0%', '1.0%', '20.0%', '5.0%', '5.0%', '-3.0%', '2.0%', '4.0%', '8.0%', '19.0%', '14.0%', '10.0%', '40.0%', '14.0%', '10.0%', '4.0%', '4.0%', '13.0%', '19.0%', '16.0%', '13.0%', '18.0%', '2.0%', '25.0%', '9.0%', '28.0%', '10.0%', '9.0%', '66.0%', '15.0%', '8.0%', '15.0%', '19.0%', '2.0%', '25.0%', '10.0%', '6.0%', '30.0%', '24.0%', '19.0%', '9.0%', '30.0%', '12.0%', '13.0%', '33.0%', '6.0%', '5.0%', '25.0%', '6.0%', '3.0%', '2.0%', '5.0%', '28.0%', '26.0%', '16.0%', '23.0%', '6.0%', '13.0%', '23.0%', '16.0%', '20.0%', '8.0%', '14.0%', '1.0%', '13.0%', '-2.0%', '17.0%', '29.0%', '37.0%', '7.0%', '13.0%', '8.0%', '23.0%', '26.0%', '4.0%', '9.0%', '5.0%', '35.0%', '2.0%', '10.0%', '12.0%', '10.0%', '12.0%', '2.0%', '6.0%', '7.0%', '1.0%', '8.0%', '11.0%', '0.0%', '11.0%', '8.0%', '16.0%', '28.0%', '6.0%', '22.0%', '1.0%', '17.0%', '22.0%', '2.0%', '9.0%', '19.0%', '19.0%', '1.0%', '40.0%', '34.0%', '22.0%', '1.0%', '-4.0%', '33.0%', '-15.0%', '4.0%', '9.0%', '3.0%', '8.0%', '11.0%', '27.0%', '29.0%', '-2.0%', '3.0%', '10.0%', '21.0%', '34.0%', '1.0%', '9.0%', '-2.0%', '-4.0%', '5.0%', '13.0%', '28.0%', '6.0%', 'nan%', '10.0%', '0.0%', '1.0%', '27.0%', '1.0%', '3.0%', '2.0%', '3.0%', '12.0%', '32.0%', '17.0%', '3.0%', '1.0%', '1.0%', '47.0%', '0.0%', '-5.0%', '8.0%', '17.0%', '1.0%', '20.0%', '24.0%', '14.0%', '2.0%', '4.0%', '44.0%', '15.0%', '2.0%', '13.0%', '-8.0%', '0.0%', '17.0%', '8.0%', '12.0%', '8.0%', '0.0%', '2.0%', '6.0%', '22.0%', '7.0%', '15.0%', '7.0%', '15.0%', '0.0%', '10.0%', '4.0%', '13.0%', '4.0%', '9.0%', '-4.0%', '18.0%', '-5.0%', '17.0%', '14.0%', '16.0%', '7.0%', '1.0%', '36.0%', '3.0%', '30.0%', '2.0%', '-13.0%', '-13.0%', '20.0%', '12.0%', '33.0%', '22.0%', '4.0%', '4.0%', '11.0%', '31.0%', '-1.0%', '0.0%', '24.0%', '33.0%', '2.0%', '7.0%', '11.0%', '8.0%', '35.0%', '-5.0%', '0.0%', '9.0%', '15.0%', '24.0%', '40.0%', '9.0%', '0.0%', '1.0%', '5.0%', '14.0%', '34.0%', '52.0%', '5.0%', '6.0%', '18.0%', '9.0%', '3.0%', '8.0%', '19.0%', '18.0%', '3.0%', '28.0%', '2.0%', '6.0%', '26.0%', '19.0%', '25.0%', '7.0%', '-10.0%', '2.0%', '15.0%', '11.0%', '24.0%', '7.0%', '1.0%', '28.0%', '7.0%', '14.0%', '3.0%', '6.0%', '5.0%', '26.0%', '29.0%', '15.0%', '17.0%', '-3.0%', '33.0%', '15.0%', '23.0%', '2.0%', '5.0%', '9.0%', '23.0%', '8.0%', '6.0%', '3.0%', '1.0%', '25.0%', '-3.0%', '15.0%', '8.0%', '5.0%', '19.0%', '26.0%', '25.0%', '179.0%', '-2.0%', '16.0%', '4.0%', '6.0%', '17.0%', '21.0%', '7.0%', '2.0%', '0.0%', '31.0%', '0.0%', '4.0%', '6.0%', '23.0%', '10.0%', '28.0%', '16.0%', '31.0%', '12.0%', '10.0%', '3.0%', '6.0%', '11.0%', '2.0%', '0.0%', '14.0%', '3.0%', '7.0%', '16.0%', '8.0%', '24.0%', '17.0%', '11.0%', '10.0%', '3.0%', '32.0%', '7.0%', '24.0%', '28.0%', '1.0%', '36.0%', '9.0%', '1.0%', '16.0%', '3.0%', '8.0%', '22.0%', '6.0%', '1.0%', '14.0%', '8.0%', '7.0%', '4.0%', '11.0%', '28.0%', '20.0%', '-11.0%', '22.0%', '22.0%', '7.0%', '15.0%', '1.0%', '-1.0%', '28.0%', '7.0%', '33.0%', '-2.0%', '26.0%', 'nan%', '8.0%', '40.0%', '1.0%', '0.0%', '13.0%', '6.0%', '8.0%', '-22.0%', '1.0%', '18.0%', '28.0%', '22.0%', '35.0%', '4.0%', '1.0%', '12.0%', '7.0%', '144.0%', '18.0%', '18.0%', '-1.0%', '9.0%', '0.0%', '5.0%', '5.0%', '6.0%', '4.0%', '2.0%', '1.0%', '12.0%', '11.0%', '24.0%', '1.0%', '0.0%', '15.0%', '80.0%', '7.0%', '19.0%', '3.0%', '13.0%', '13.0%', '8.0%', '20.0%', '2.0%', '24.0%', '50.0%', '-5.0%', '20.0%', '19.0%', '13.0%', '-60.0%', '19.0%', '22.0%', '-1.0%', '-2.0%', '26.0%', '0.0%', '13.0%', '2.0%', '0.0%', '47.0%', '39.0%', '5.0%', '16.0%', '41.0%', '27.0%', '12.0%', '42.0%', '4.0%', '35.0%', '4.0%', '7.0%', '14.0%', '14.0%', '-2.0%', '5.0%', '22.0%', '14.0%', '7.0%', '2.0%', '-6.0%', '3.0%', '18.0%', '7.0%', '1.0%', '7.0%', '6.0%', '10.0%', '-253.0%', '3.0%', '6.0%', '-4.0%', '2.0%', '6.0%', '16.0%', '1.0%', '-5.0%', '31.0%', '2.0%', '3.0%', '0.0%', '16.0%', '-1.0%', '4.0%', '-1.0%', '23.0%', '2.0%', '20.0%', '25.0%', '37.0%', '6.0%', '3.0%', '33.0%', '2.0%', '10.0%', '2.0%', '1.0%', '-1.0%', '5.0%', '6.0%', '4.0%', '4.0%', '6.0%', '1.0%', '26.0%', '21.0%', '14.0%', '36.0%', '3.0%', '27.0%', '1.0%', '6.0%', '12.0%', '-8.0%', '7.0%', '20.0%', '4.0%', '19.0%', '-34.0%', '50.0%', '20.0%', '7.0%', '16.0%', '16.0%', '26.0%', '13.0%', '12.0%', '22.0%', '6.0%', '16.0%', '-2.0%', '10.0%', '0.0%', '18.0%', '20.0%', '12.0%', '16.0%', '4.0%', '15.0%', '38.0%', '0.0%', '7.0%', '3.0%', '24.0%', '17.0%', '25.0%', '12.0%', '-4.0%', '7.0%', '20.0%', '17.0%', '13.0%', '3.0%', '18.0%', '33.0%', '23.0%', '-3.0%', '34.0%', '6.0%', '11.0%', '17.0%', '21.0%', '15.0%', '19.0%', '2.0%', '29.0%', '2.0%', '8.0%', '1.0%', '18.0%', '0.0%', '35.0%', '10.0%', '10.0%', '4.0%', '16.0%', '0.0%', '42.0%', '0.0%', '4.0%', '3.0%', '2.0%', '12.0%', '3.0%', '20.0%', '23.0%', '3.0%', '3.0%', '20.0%', '2.0%', '17.0%', '1.0%', '15.0%', '7.0%', '18.0%', '1.0%', '-3.0%', '7.0%', '6.0%', '60.0%', '15.0%', '23.0%', '21.0%', '0.0%', '18.0%', '25.0%', '4.0%', '-8.0%', '1.0%', '4.0%', '18.0%', '27.0%', '2.0%', '6.0%', '3.0%', '4.0%', '20.0%', '17.0%', '6.0%', '1.0%', '2.0%', '0.0%', '5.0%', '3.0%', '19.0%', '5.0%', '7.0%', '8.0%', '12.0%', '40.0%', '21.0%', '13.0%', '16.0%', '7.0%', '17.0%', '27.0%', '0.0%', '28.0%', '1.0%', '9.0%', '8.0%', '15.0%', '10.0%', '-1.0%', '11.0%', '12.0%', '6.0%', '1.0%', '69.0%', '17.0%', '8.0%', '-16.0%', '5.0%', '26.0%', '19.0%', '2.0%', '8.0%', '14.0%', '17.0%', '24.0%', '0.0%', '12.0%', '18.0%', '50.0%', '9.0%', '4.0%', '13.0%', '6.0%', '22.0%', '9.0%', '32.0%', '4.0%', '30.0%', '4.0%', '5.0%', '2.0%', '19.0%', '3.0%', '16.0%', '24.0%', '10.0%', '-17.0%', '0.0%', '5.0%', '1.0%', '2.0%', '2.0%', '25.0%', '26.0%', '20.0%', '5.0%', '0.0%', '-3.0%', '0.0%', '4.0%', '1.0%', '30.0%', '15.0%', '10.0%', '7.0%', '35.0%', '2.0%', '38.0%', '32.0%', '-6.0%', '87.0%', '-4.0%', '2.0%', '6.0%', '31.0%', '3.0%', '18.0%', '1.0%', '27.0%', '8.0%', '23.0%', '32.0%', '8.0%', '15.0%', '18.0%', '24.0%', '2.0%', '-1.0%', '0.0%', '-57.0%', '18.0%', '17.0%', '-1.0%', '8.0%', '10.0%', '20.0%', '0.0%', '3.0%', '-8.0%', '4.0%', '6.0%', '42.0%', '1.0%', '6.0%', '2.0%', '18.0%', '28.0%', '21.0%', '10.0%', '22.0%', '14.0%', '6.0%', '19.0%', '14.0%', '29.0%', '24.0%', '8.0%', '19.0%', '25.0%', '-5.0%', '17.0%', '20.0%', '-1.0%', '0.0%', '14.0%', '-7.0%', '20.0%', '38.0%', '31.0%', '13.0%', '16.0%', '10.0%', '-15.0%', '16.0%', '41.0%', '14.0%', '6.0%', '3.0%', '100.0%', '-1.0%', '13.0%', '14.0%', '22.0%', '9.0%', '0.0%', '-2.0%', '5.0%', '20.0%', '40.0%', '39.0%', '49.0%', '15.0%', '11.0%', '-6.0%', '5.0%', '-1.0%', '5.0%', '4.0%', '8.0%', '13.0%', '-4.0%', '310.0%', '0.0%', '5.0%', '19.0%', '1.0%', '1.0%', '11.0%', '14.0%', '4.0%', '411.0%', '5.0%', '4.0%', '22.0%', '-9.0%', '5.0%', '28.0%', '12.0%', '1.0%', '9.0%', '6.0%', '0.0%', '13.0%', '-1.0%', '2.0%', '1.0%', '0.0%', '-1.0%', '16.0%', '6.0%', '22.0%', '1.0%', '36.0%', '12.0%', '85.0%', '5.0%', '194.0%', '16.0%', '12.0%', '9.0%', '11.0%', '47.0%', '21.0%', '3.0%', '15.0%', '2.0%', '21.0%', '4.0%', '0.0%', '20.0%', '-3.0%', '3.0%', '9.0%', '25.0%', '21.0%', '-1.0%', '5.0%', '19.0%', '0.0%', '8.0%', '3.0%', '1.0%', '4.0%', '17.0%', '26.0%', '-16.0%', '21.0%', '-9.0%', '41.0%', '2.0%', '18.0%', '10.0%', '23.0%', '2.0%', '16.0%', '7.0%', '24.0%', '-8.0%', '1.0%', '0.0%', '7.0%', '4.0%', '5.0%', '21.0%', '21.0%', '2.0%', '2.0%', '12.0%', '15.0%', '1.0%', '8.0%', '2.0%', '17.0%', '13.0%', '0.0%', '0.0%', '2.0%', '6.0%', '2.0%', '5.0%', '1.0%', '23.0%', '-5.0%', '8.0%', '21.0%', '7.0%', '58.0%', '3.0%', '-36.0%', '13.0%', '-15.0%', '28.0%', '122.0%', '-1.0%', '5.0%', '0.0%', '-1.0%', '18.0%', '8.0%', '16.0%', '-2.0%', '12.0%', '20.0%', '9.0%', '5.0%', '3.0%', '30.0%', '1.0%', '7.0%', '18.0%', '3.0%', '-1.0%', '15.0%', '12.0%', '12.0%', '18.0%', '28.0%', '17.0%', '16.0%', '3.0%', '0.0%', '-26.0%', '2.0%', '30.0%', '13.0%', '17.0%', '-3.0%', '7.0%', '664.0%', '9.0%', '48.0%', '1.0%', '4.0%', '1.0%', '16.0%', '66.0%', '28.0%', '0.0%', '18.0%', '16.0%', '-5.0%', '-4.0%', '35.0%', '15.0%', '3.0%', '-2.0%', '3.0%', '5.0%', '0.0%', '22.0%', '0.0%', '11.0%', '4.0%', '106.0%', '-4.0%', '11.0%', '13.0%', '-68.0%', '1.0%', '45.0%', '18.0%', '12.0%', '8.0%', '5.0%', '16.0%', '1.0%', '14.0%', '-17.0%', '-16.0%', '1.0%', '10.0%', '28.0%', '4.0%', '23.0%', '18.0%', '3.0%', '24.0%', '0.0%', '49.0%', '0.0%', '15.0%', '48.0%', '1.0%', '-2.0%', '0.0%', '42.0%', '4.0%', '3.0%', '5.0%', '21.0%', '1.0%', '12.0%', '23.0%', '-19.0%', '22.0%', '6.0%', '3.0%', '5.0%', '2.0%', '44.0%', '19.0%', '-8.0%', '1.0%', '6.0%', '15.0%', '8.0%', '3.0%', '1.0%', '-3.0%', '18.0%', '3.0%', '14.0%', '11.0%', '9.0%', '1.0%', '14.0%', '-1.0%', '4.0%', '10.0%', '21.0%', '-1.0%', '12.0%', '-13.0%', '9.0%', '9.0%', '0.0%', '3.0%', '15.0%', '-1.0%', '7.0%', '0.0%', '0.0%', '19.0%', '8.0%', '71.0%', '1.0%', '12.0%', '-6.0%', '6.0%', '7.0%', '5.0%', '24.0%', '3.0%', '26.0%', '20.0%', '17.0%', '18.0%', '17.0%', '6.0%', '24.0%', '11.0%', '28.0%', '11.0%', '14.0%', '24.0%', '0.0%', '4.0%', '1.0%', '2.0%', '2.0%', '15.0%', '301.0%', '14.0%', '6.0%', '3.0%', '25.0%', '15.0%', '9.0%', '-45.0%', '1.0%', '21.0%', '4.0%', '6.0%', '13.0%', '17.0%', '5.0%', '11.0%', '63.0%', '20.0%', '11.0%', '8.0%', '12.0%', '11.0%', '24.0%', '0.0%', '20.0%', '-5.0%', '24.0%', '10.0%', '0.0%', 'nan%', '5.0%', '-19.0%', '4.0%', '8.0%', '2.0%', '17.0%', '1.0%', '7.0%', '0.0%', '1.0%', '25.0%', '28.0%', '22.0%', '11.0%', '-1.0%', '16.0%', '18.0%', '16.0%', '17.0%', '4.0%', '3.0%', '28.0%', '18.0%', '-15.0%', '8.0%', '-17.0%', '4.0%', '0.0%', '2.0%', '13.0%', '1.0%', '6.0%', '42.0%', '21.0%', '27.0%', '0.0%', '6.0%', '18.0%', '-61.0%', '21.0%', '57.0%', '24.0%', '1.0%', '19.0%', '1.0%', '5.0%', '7.0%', '22.0%', '0.0%', '1.0%', '-4.0%', '3.0%', '2.0%', '0.0%', '11.0%', '1.0%', '12.0%', '3.0%', '43.0%', '8.0%', '29.0%', '3.0%', '57.0%', '13.0%', '23.0%', '16.0%', '-15.0%', '16.0%', '8.0%', '16.0%', '1.0%', '10.0%', '-9.0%', '0.0%', '0.0%', '4.0%', '20.0%', '2.0%', '2.0%', '9.0%', '-2.0%', '17.0%', '6.0%', '0.0%', '14.0%', '10.0%', '5.0%', '30.0%', '7.0%', '19.0%', '17.0%', '66.0%', '11.0%', '-14.0%', '11.0%', '4.0%', '16.0%', '2.0%', '15.0%', '34.0%', '4.0%', '0.0%', '48.0%', '2.0%', '-8.0%', '7.0%', '6.0%', '1.0%', '1.0%', '8.0%', '20.0%', '3.0%', '7.0%', '12.0%', '-22.0%', '1.0%', '9.0%', '278.0%', '20.0%', '0.0%', '28.0%', '77.0%', '13.0%', '2.0%', '-13.0%', '4.0%', '29.0%', '-10.0%', '6.0%', '30.0%', '330.0%', '3.0%', '2.0%', '63.0%', '-1.0%', '11.0%', '0.0%', '-15.0%', '0.0%', '25.0%', '38.0%', '13.0%', '23.0%', '27.0%', '2.0%', '-1.0%', '-10.0%', '6.0%', '12.0%', '-32.0%', '2.0%', '24.0%', '10.0%', '1.0%', '14.0%', '11.0%', '-38.0%', '14.0%', '7.0%', '-1.0%', '1.0%', '12.0%', '6.0%', '7.0%', '2.0%', '22.0%', '10.0%', '3.0%', '15.0%', '16.0%', '3.0%', '121.0%', '13.0%', '23.0%', '5.0%', '0.0%', '7.0%', '19.0%', '164.0%']

In [98]:
df["Profit Margin"] = l

In [99]:
df.head()

,Rank,Company,Headquarters,Industry,Sales,Profit,Assets,Market Value,profit Margin,Profit Margin
0,1,JPMorganChase,United States,Banking,285.11,59.36,4357.86,677.80,0.208200,20.0%
1,2,Berkshire Hathaway,United States,Insurance,371.43,89.00,1153.88,1145.46,0.239614,23.0%
2,3,ICBC,China,Banking,221.96,50.84,6688.60,251.33,0.229050,22.0%
3,4,Saudi Arabian Oil Company (Saudi Aramco),Saudi Arabia,Oil & Gas Operations,480.15,104.97,645.03,1663.38,0.218619,21.0%
4,5,Amazon,United States,Retail and Wholesale,637.96,59.25,624.89,2005.64,0.092874,9.0%

In [102]:
north_america = []
south_america = []
asia = []
europe = []
middle_east = []
australia = []

for i in country:
    if i in ["Canada","Colombia" , "United States" , "Chile"]:
        north_america.append(i)
    elif i in ["Brazil","Argentina" , "Mexico"]:
         south_america.append(i)
    elif i in ["China" , "India" ,"Hong Kong" , "Indonesiya" , "Malaysia","Singapore" , "South Korea" , "Taiwan" , "Thailand" , "Vietnam"]:
        asia.append(i)
    elif i in ["Czech Republic" , "Israel" , "Kazakhstan" , "Kuwait" , "Qatar" , "Saudi Arabia"]:
        Middle_east.append(i)
    elif i in ["Australia"]:
        australia.append(i)
    else:
        eurpoe.append(i)

NameError: name 'country' is not defined

In [ ]:
region  = []
for i in df["Headquarters"]:
     if i in north_america:
         region.append("North America")
     elif i in south_america:
         region.append("South Amrica")
     elif i in asia:
         region.append(Asia)
     elif i in middle_east:
         region.append("Middle_east")
     elif i in australia:
         region.append("Austraia")
     elif i in europe:
         region.append("Europe")

In [ ]:
df["region"] = region

In [ ]:
df

In [103]:
for i , j in enumerate(df["Sales"]):
    if j == 0:
        print(i)

1820

In [104]:
df.loc[1820 , "sales"] = 1

In [105]:
df["MV/Sales Ratio"] = df["Market Value"] / df["Sales"]
df

,Rank,Company,Headquarters,Industry,Sales,Profit,Assets,Market Value,profit Margin,Profit Margin,sales,MV/Sales Ratio
0,1,JPMorganChase,United States,Banking,285.110,59.3600,4357.86,677.800,0.208200,20.0%,NaN,2.377328
1,2,Berkshire Hathaway,United States,Insurance,371.430,89.0000,1153.88,1145.460,0.239614,23.0%,NaN,3.083919
2,3,ICBC,China,Banking,221.960,50.8400,6688.60,251.330,0.229050,22.0%,NaN,1.132321
3,4,Saudi Arabian Oil Company (Saudi Aramco),Saudi Arabia,Oil & Gas Operations,480.150,104.9700,645.03,1663.380,0.218619,21.0%,NaN,3.464292
4,5,Amazon,United States,Retail and Wholesale,637.960,59.2500,624.89,2005.640,0.092874,9.0%,NaN,3.143833
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Dino Polska,Poland,Food Markets,7.360,0.3781,3.16,13.840,0.051372,5.0%,NaN,1.880435
1996,1997,China Aviation Oil,Singapore,Trading Companies,15.520,0.0784,1.99,0.559,0.005052,0.0%,NaN,0.036018
1997,1998,Jet2,United Kingdom,Business Services & Supplies,8.790,0.6288,7.95,3.930,0.071536,7.0%,NaN,0.447099
1998,1998,Keiyo Bank,Japan,Banking,0.474,0.0927,42.56,0.679,0.195570,19.0%,NaN,1.432489
1999,1998,PT Lippo Karawaci,Indonesia,Construction,0.716,1.1800,3.34,0.366,1.648045,164.0%,NaN,0.511173

In [2]:
company = df.groupby("Company")['MV/Sales Ratio'].sum()
company.sort_values(ascending = False)[:5].plot(kind = "bar")

NameError: name 'df' is not defined

In [1]:
industry = df.groupby("Industry")['MV/Sales Ratio'].mean()
industry.sort_values(ascending = False).head(5).plot(Kind = "bar")

NameError: name 'df' is not defined